### ISSUE TITLE
Blank page and device type

### ISSUE THREAD

**Issue by 4tetra4** [soler2000/com.lightwaverf#14]
Hi Andy,

Finally I got my homey, had a little time to test the app. It looks great and quite comprehensive. Two thing I found:

1., When I successfully pair a device there is a blank page after the `testing page`. I am not sure if anything should be displayed there or just accidentally stayed there.

2., I have some standing lamp and bedside lamps plugged into a lightwaveRF socket. The thing is that is not recognised by homey as light. So when I say Please turn on the light in the living room. It says I could not find any light in the living room. So I deleted the socket and went to add a dimmer and when in linking mode I pressed the button on the socket. This way it is recognised as lighting. 
However it is not the best way as dimming can be problematic with an on/off device. Would it be possible to add an option to set the type of the socket as lighting, etc?

**Comment by soler2000** [comment]
This will be fixed in the next release,  this was broken in 0.8.30 and has now been addressed

**Comment by soler2000** [comment]
Should be fixed in the master now

**Comment by soler2000** [comment]
Fixed now, will be pushed to the app store.
