### ISSUE TITLE
Remote is not working in the flow

### ISSUE THREAD

**Issue by 4tetra4** [soler2000/com.lightwaverf#15]
Hi Andy,

I have added a remote. The pairing went well. On the testing page it gave the result. However it does not work in the flow. I have 0.8.30.

**Comment by soler2000** [comment]
I am aware of this, this bug was introduced in 0.8.30

**Comment by soler2000** [comment]
Should be fixed in the master now

**Comment by soler2000** [comment]
Fixed now,  will be pushed to app store
