### ISSUE TITLE
LW 2100 Slow

### ISSUE THREAD

**Issue by chinswain** [soler2000/com.lightwaverf#18]
Is it possible to get an immediate trigger from the LW 2100 push button (trigger card on device ID?) rather than waiting for all data? (I'm noticing a 5 second delay) The slow response could cause problems for notification uses.

**Comment by soler2000** [comment]
The Lightwave door bell is a mash up of two devices,  One is the doorbell protocol set of unknown code followed by the standard lightwave protocol,  Unfortunately the doorbell protocol is transmitted first and only when the Lightwave Command set starts does Homey decode the first valid signal set received.   Unfortunately there is no way around this without know the first protocol.
