### ISSUE TITLE
Unable to add devices since last Homey update (1.0.3)

### ISSUE THREAD

**Issue by chinswain** [soler2000/com.lightwaverf#25]
The LightwaveRF app crashes with the following log upon activating devices recently added:

Stack trace:

TypeError: Cannot read property 'address' of undefined
at Object.<anonymous> (/drivers/doorbell.js:478:47)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:211
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 1
Exit signal: null

**Comment by soler2000** [comment]
Trying to understand this,   On old devices it works as expected but on new devices it crashes?  Is this correct.

**Comment by chinswain** [comment]
Hi Andy,

I've not added or removed any devices for some time - today I had to replace the batteries in the bell, for some reason this caused it to disappear from the devices. Trying to add it back causes that error (and the app to crash) as soon as the newly added device is used in a flow.

**Comment by soler2000** [comment]
ok,  so its just the bell.  Let me check into it.  There was an update that Athom did after a device firmware change to Homey and possibly they missed the bell driver

**Comment by chinswain** [comment]
Fixed by pull request #27
