### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ArchiSpec** [soler2000/com.lightwaverf#28]
Hi - is the install broken? Cannot install app - gives error "signals.433.lwrf: invalid_sensitivity"

Homey version 1.3.1

**Comment by chinswain** [comment]
Hi,

Yes - you need to manually install it from this repository (which is fixed), the version on the App store is behind.

**Comment by ArchiSpec** [comment]
Thanks for such a quick reply. 

Sorry, I'm newbie - are there instructions somewhere on how to do this?

Thankyou.

**Comment by chinswain** [comment]
Try this: https://forum.athom.com/discussion/1448/how-to-cli-install-method

**Comment by ArchiSpec** [comment]
That's great, working fine now. Thank you.

Two questions:

- are you planning support for the 2-gang wireless dimmer? Only 1-gang listed, tried adding each side separately, but just seems to treat both as one.

- and does the mood remote work with all buttons, or only on and off? (I don't have one yet!)

Thanks for your help.

**Comment by soler2000** [comment]
2 gang support is working,  only the icon shows a single gang,  you will need to add a device for each of the switches,  same applies to plugs etc.

Remotes are supported but to be honest I have seen quite a lot of variation in the remotes and some work and some don't,  it is a bit of pot luck I'm afraid.  However they will still work directly with the device so you can bypass homey if needed.

**Comment by ArchiSpec** [comment]
Thanks. I had tried adding each side individually, but they get treated as one, so both sides end up doing the same thing....

With the lw101 mood switch, initial setup up with the on and off buttons works (i.e. turns on the on-screen light bulb) but after registration, only the 3 mood buttons and all off work (although a little haphazardly), not the large on and off buttons. Strange as they are recognised at setup. I've tried several units. Is there any tinkering which can be done? Not linked directly to LW switches - intending to use the lw101s purely as mood controllers for Homey flows. Is there anything that can be done?

Appreciate your assistance. 

ps tried with both the old style 101 and the new style 101a - same result as above. Enquired with Lightwave and they say they use identical hardware / codes, just the faceplate is different.

**Comment by soler2000** [comment]
It should be able to differentiate from one side to another,  when pairing one side let the wizard do the full cycle and close,  then add the other side in the same process.   If you add them both while he wizard is open it will send the same code twice and appear to be treated as one.

**Comment by ArchiSpec** [comment]
Hi, yes added each side separately of course. Each test OK during pairing. But once you create a flow with one side, the other side will do exactly the same thing and vice-versa.

Also the large on/off buttons on the mood controller not working in flows, even though they work at pairing. Only the 4 smaller mood buttons work in flows.

Hope to hear.

**Comment by soler2000** [comment]
Very strange for the two sided switch,  I have them here and they work flawlessly,   during the pairing the wizard generates a new random code and the lightwave switch should pair with it.  DO you have any other Lightwave switches? and are these working as normal?

For the mood controller there is a switch on the side to change the mode,  can you try flipping that to see if it makes a difference.

**Comment by ArchiSpec** [comment]
Ah, changing the switch on the back of the mood controller to the "M" setting works a treat - all buttons now work (LW101). THANK YOU!!!

Now, the only problem is that the new-style LW101a doesn't have such a switch on the back...... are you able to do an update for the new-style mood controller LW101a (LW technical said the hardware /codes were identical, but clearly that's not the case if that switch is not even there on the hardware!).

And finally, the 2-gang wireless dimmer - I only have the one, so cannot check, but it is brand new. I've tried many times now, adding each side separately, but end up with the same result. 

Thanks again for all your help. It is much appreciated.

**Comment by ArchiSpec** [comment]
Any possibility of supporting the new-style LW101a as above? Without the switch on the back.....

**Comment by soler2000** [comment]
I don't have the switch you referring to so I am not sure how the codes differ from the old style.  Sorry for that

**Comment by soler2000** [comment]
Original topic of install error is closed

**Comment by ArchiSpec** [comment]
> Now, the only problem is that the new-style LW101a doesn't have such a switch on the back...... are you able to do an update for the new-style mood controller LW101a (LW technical said the hardware /codes were identical, but clearly that's not the case if that switch is not even there on the hardware!).

> I don't have the switch you referring to so I am not sure how the codes differ from the old style. Sorry for that

Hi, just to raise this question again - sorry but I have more information now which may enable you to implement this?

I have been in touch again with LightwaveRF and they tell me that the new LW101a definitely uses the same codes, its just that it doesn't have the switch on the back to change to "M" mode. So the question is, is it possible for you to implement the codes that the LW101 (that you do have) uses for the two large buttons when in the "O/I" position (right) rather than the "M" position (left)? If this is possible, it WOULD then work with the new style as well, so I am told.

I hope that makes sense, basically using the model you do have but with the switch set in the right, not the left, position.

Hope you can help. Thanks.
