### ISSUE TITLE
Limited Range

### ISSUE THREAD

**Issue by rabell79** [soler2000/com.lightwaverf#29]
Recently purchased my homey and got the wireless switches working in a flow but the range is very poor, only reliably works in the same room. Logged a ticket with Athom and Emile suggested checking here to see if there are plans to optimise the app (suggested looking at the signal definitions). Anyone else having range issues, any plans to optimise?

**Comment by soler2000** [comment]
I have done what I can with the app for the signal definition,  it seam that the light wave remotes are not consistent in quality and while optimising for one remote it means that other remotes are less sensitive.  Lightwave decode there signals via hardware which are more tolerant of the differences but homey has to do this is software and it seams less tolerant.

Unless there is a significant change in the Homey software that allows it to be more fault tolerant then there is not much I can do.  If your interested in experimenting look at file app.json and the following code on lines 650 to 655.  

I would only look at changing manchesterUnit and sensitivity.   manchesterUnit I had success between 300 and 350,  sensitivity can be from 0.1 to 0.9.

                "manchesterUnit": 325,
                "manchesterMaxUnits": 9,
                "interval": 10500,
                "repetitions": 20,
                "sensitivity": 0.5, 

Unfortunately it depends on the remote and the values used are a compromise based on the data recorded from the remotes I measured.

**Comment by soler2000** [comment]
Closed as above
